# Generated by Django 4.1.1 on 2023-05-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
