# Generated by Django 4.1.1 on 2023-06-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_alter_comment_body_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='MainApp.profile'),
        ),
    ]
