# Generated by Django 4.1.1 on 2023-06-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Notes', to='MainApp.profile'),
        ),
    ]
