# Generated by Django 4.1.1 on 2023-07-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_debate_author_debate_opponent'),
        ('poll', '0004_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='MainApp.category'),
        ),
    ]
