# Generated by Django 4.1.1 on 2023-07-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_poll_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
